# Generated by Django 6.0.3 on 2026-03-04 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solohub', '0003_rename_contacts_to_counterparts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='workspacemember',
            name='user_id',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='counterpart',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparts', to='solohub.company'),
        ),
        migrations.AlterField(
            model_name='counterpart',
            name='counterpart_type',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer'), ('both', 'Both'), ('individual', 'Individual')], default='vendor', max_length=10),
        ),
        migrations.AlterField(
            model_name='counterpart',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparts', to='solohub.workspace'),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
